// Researched supplier list (Oct 2026). Prices/times as published or reported; always confirm on the supplier's site.
const SUP = (() => {
  const TYPES = { tumbler: 'Engraved tumblers (skinny / 40oz)', wood: 'Engraved wood (photo plaques, business cards)', blanket: 'Embroidered baby blankets / bibs', book: "Personalized children's books", crystal: '3D crystal photo keepsakes', apparel: 'Sweatshirts & tees (POD)', basket: 'Personalized rope baskets / yarn names', other: 'Something else' };
  const LIST = [
    { n: 'Printify', u: 'https://printify.com/custom-engraving/', t: ['tumbler', 'wood', 'apparel'], etsy: 'Yes (native)', p: 'Engraved 40oz tumbler ~$28.18 + $9.79 US ship (third-party tracker); Gildan 18000 sweatshirt ~$15.24 ($11.22 Premium)', time: '2-7 business days production (Printify help)', note: 'No minimums. Engraving catalog is mostly glass, wood boards, leather, jewelry; few tumblers.' },
    { n: 'Printful', u: 'https://www.printful.com/custom/blankets/personalized/embroidered-premium-sherpa-blanket-port-authority-bp40', t: ['blanket', 'apparel'], etsy: 'Yes (native, supports Etsy personalization as drafts)', p: 'Embroidered Premium Sherpa Blanket (50x60 in) ~$45.90-46.82', time: '2-5 business days avg fulfillment', note: 'Adult-size blanket, not a baby blanket; strong embroidery reviews.' },
    { n: 'Gooten', u: 'https://www.gooten.com/print-on-demand/tumblers/', t: ['tumbler', 'apparel'], etsy: 'Yes', p: 'Not published on catalog page', time: 'Not published on catalog page', note: 'Has a 40oz Eco-Friendly Straw Tumbler with laser decoration; 20oz skinny is printed, not engraved.' },
    { n: 'Gelato', u: 'https://www.gelato.com/products/childrens-books', t: ['book', 'apparel'], etsy: 'Yes (native)', p: 'Not published on product page', time: '~5-6 days to delivery on average', note: 'Built-in personalization tool for storybooks; 7 formats up to 200 pages; soft and hardcover.' },
    { n: 'LazerDesigns (Colorado)', u: 'https://www.lazerdesigns.com/dropship', t: ['wood', 'tumbler'], etsy: 'Allowed (some restrictions); orders by email/CSV', p: 'Discount off site prices; quote on request', time: 'Ships most partner orders in 1-3 business days', note: 'Not automated; prepay; needs reseller certificate. In business since 2001.' },
    { n: 'Laser Fulfilment UK', u: 'https://laserfulfilment.co.uk/', t: ['wood', 'crystal'], etsy: 'Via ShipStation / order file / Shopify Marketplace Connect', p: 'Shown in their catalog after signup', time: 'Made in & shipped from UK', note: 'No minimum, no monthly fee, branded packaging. UK origin = slower/costlier for US buyers.' },
    { n: 'AI Printfinity (Florida)', u: 'https://aiprintfinity.com/', t: ['tumbler'], etsy: 'Yes (Etsy API)', p: 'Starter $49/mo + $0.40/label + $1.50/engraving', time: 'Same-day USPS dispatch for orders by 2pm ET', note: 'US fulfillment for reseller teams; clarify who supplies blanks before signing up.' },
    { n: 'Engraved in 3D', u: 'https://www.engravedin3d.com/', t: ['crystal'], etsy: 'Dropship (manual / white-label)', p: 'Orders from $10 (per their site listing)', time: '3-5 day turnaround (per their site listing)', note: 'No minimums, no setup fee, ships direct to your customer.' },
    { n: 'Yiwu Shining Crystal', u: 'https://www.yiwushiningcrystal.com/personalized-3d-photo-crystals', t: ['crystal'], etsy: 'No (wholesale/OEM)', p: 'Quote on request', time: 'Ships from China', note: 'Factory for K9 crystal with 2D/3D photo engraving.' },
    { n: 'OiaHomy (Hangzhou Veinuo)', u: 'https://oiahomywholesale.com/', t: ['basket'], etsy: 'No (wholesale)', p: 'Quote; MOQ 200/style (small trial orders on some stock)', time: '~2 weeks from US warehouse for stock items', note: 'Cotton rope basket factory with US warehouse and custom/OEM work.' },
    { n: 'MTH Vietnam (Alibaba)', u: 'https://www.alibaba.co.uk/product-detail/Personalized-Baby-Name-Cotton-Rope-Baskets_1601308819816.html', t: ['basket'], etsy: 'No (wholesale)', p: '£1.54-3.07 each, MOQ 50', time: '35-day lead time', note: '"Personalized Baby Name Cotton Rope Baskets", Hanoi; no reviews yet.' },
    { n: 'Cool Apparel (Made-in-China)', u: 'https://coolapparel.en.made-in-china.com/product/CxpYutIUVirB/China-Custom-Ruffle-Monogrammed-Bibs-with-Baby-Name-Embroidery.html', t: ['blanket'], etsy: 'No (wholesale)', p: 'US$1.25, MOQ 100', time: 'Samples 3-7 days', note: 'Muslin ruffle bibs with name embroidery; CPC/CPSIA listed.' },
    { n: 'VNAP (Alibaba, Vietnam)', u: 'https://www.alibaba.co.uk/product-detail/HIGHT-QUALITY-EMBROIDERY-BABY-BIB-PREMIUM_10000023879096.html', t: ['blanket'], etsy: 'No (wholesale)', p: '$1.20-2.50, MOQ 50', time: '7 days for 1-50 pcs', note: 'Embroidered cotton bibs, custom designs.' },
  ];
  const SEARCH = [
    { n: 'Google Lens', u: 'https://lens.google.com/', how: 'Click the camera/upload icon and choose your photo. Look at "Visual matches" for factory and wholesale listings.' },
    { n: 'AliExpress', u: 'https://www.aliexpress.us/', how: 'Click the camera icon in the search bar and upload the photo (works best in the AliExpress app).' },
    { n: 'Alibaba', u: 'https://www.alibaba.com/', how: 'Click the camera icon in the search bar, upload the photo, then filter by "Verified supplier".' },
    { n: 'Bing Visual Search', u: 'https://www.bing.com/visualsearch', how: 'Upload the photo; good second opinion to Google Lens.' },
    { n: 'Temu', u: 'https://www.temu.com/', how: 'Camera icon in the search bar (app). Same factories often sell here; good for price checks.' },
  ];
  return { TYPES, LIST, SEARCH };
})();
